services:
  db:
    image: postgres:16-alpine
    container_name: sentinel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: "X9p4#vJm3Lq8@Ns2Rz7!Te5kWb1Hg6D"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
